---
title: "STAT 250D Week 3 Activity"
author: "NAMES"
format: html
embed-resources: true
html-math-method: mathml
execute: 
  warning: false
  echo: true
  error: true
---

### LT 4: I can evaluate the summary statistics and data visualizations in support of a conclusion about a parameter(s) within the context of the study.  


Edit the **hints** below to the names of the packages, then run the code chunk to read in the necessary packages.  

```{r}
#| label: setup

library(__graphics package__)
library(__stats package__)
```


#### 1.   

Insert a code chunk and read in the King County data, store it in an object named `king`.  

< Insert code chunk >


#### 2. 

We want to explore what impacts infant birth weight. Choose ONE of the following research questions (**Bold** your choice) and rewrite it as a *statistical* research question below.    

A. Do women who smoked during pregnancy have babies with lower birth weights?  
B. Do women who drank regularly during pregnancy have babies with lower birth weights?  
C. Do women who participated in the First Steps program have babies with higher birth weights?  

> Insert statistical research question (Be sure to include your parameter(s) of interest)  



#### 3.

Create both graphics and statistics to help understand your question.

< Insert code chunks, as needed >



#### 4.

Provide an answer to your research question, with a description of what you discover using the summary statistics/graphics as evidence. Be sure to assess your evidence as a whole, and make a conclusion about the parameter(s) in context.  

> Write your answer here  



#### 5.

List any limitations of your evaluation of the research question. (i.e., Discuss the scope of generalizability. Are you able to make cause-and-effect conclusions?)

> Write your answer here  



